# Generated by Django 5.1.5 on 2025-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('people', models.CharField(max_length=10)),
                ('chapter', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('list', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novel',
            },
        ),
    ]
